/**
 * The audit found a whole year's activity on the first short advance, and a
 * 720-day war party returning without its posting being resolved. These tests
 * enter through the played world's driver, including a SQLite restart. A bill
 * falls due once on its date; a party's posting survives until its actual return.
 * Red-checked by removing the date guard and retained-posting settlement.
 */
import { describe, expect, it } from 'vitest';
import { makeDb } from '../../web/harness';
import { WorldStateRepository } from '../../../src/storage/repos/world-state.repo';
import { seedWorld } from '../../../src/engine/world/seeding';
import { fixtureCatalog } from './fixtures';
import { advanceWorldForPlay } from '../../../src/engine/world/driver';
import { cloneWorld } from '../../../src/engine/world/world-state';
import { createNpc } from '../../../src/engine/world/npc-state';
import { getSendingReason } from '../../../src/data/cultivation/why-a-house-puts-a-party-on-the-road';
import { postingFor } from '../../../src/engine/world/who-goes-out-for-a-house-and-what-comes-back';
import { isLostTrackOf } from '../../../src/engine/world/who-a-house-has-lost-track-of';

function quietWorld(seed: string) {
    const state = seedWorld({ seed, catalog: fixtureCatalog(), presentYear: 1000, population: 0 }).state;
    const house = state.factions[0]!;
    state.factions = [house];
    state.npcs = [];
    state.schedule = [];
    state.populationTarget = 0;
    state.locations.forEach(place => { place.cycle = null; place.controllingFactionId = null; });
    house.resources = { spirit_stones: 100_000, levy_per_year: 1000 };
    return state;
}

const move = (state: ReturnType<typeof quietWorld>, days: number) =>
    advanceWorldForPlay(state, { days, pressure: { intensity: 0 } });

describe('a year reached in pieces', () => {
    it('retains a war posting generated by the live sending appointment', () => {
        let found: ReturnType<typeof quietWorld> | undefined;
        for (let attempt = 0; attempt < 200 && !found; attempt++) {
            const state = quietWorld(`war-dispatch-${attempt}`);
            const house = state.factions[0]!;
            const enemy = seedWorld({ seed: state.seed, catalog: fixtureCatalog(),
                presentYear: 1000, population: 0 }).state.factions[1]!;
            state.factions.push(enemy);
            house.standing[enemy.id] = -1;
            state.currentDay += 174;
            state.npcs = Array.from({ length: 45 }, (_, i) => createNpc(state.seed, {
                id: `party-${i}`, name: `Member ${i}`, bornOnDay: state.currentDay - 30 * 365,
                onDay: state.currentDay, factionId: house.id, locationId: house.seatLocationId,
                cultivation: { realmOrdinal: 16 }
            }));
            move(state, 1);
            if (state.pendingSendings?.some(row => row.posting.reason.id === 'sending-to-a-war')) found = state;
        }
        expect(found, 'a hostile house with a spare party can dispatch a war posting').toBeDefined();
        const posting = found!.pendingSendings!.find(row => row.posting.reason.id === 'sending-to-a-war')!;
        expect(posting.party.length).toBeGreaterThan(0);
        expect(posting.departsOnDay + posting.posting.days).toBeGreaterThan(found!.currentDay);
        expect(found!.history.facts.some(f => f.kind === 'war' && f.truth === 'unresolved'
            && f.actors.some(actor => posting.party.some(member => member.id === actor.id)))).toBe(true);
    });

    it('keeps the bill for later, pays once, and resumes after a saved partial year', () => {
        const state = quietWorld('appointments');
        const houseId = state.factions[0]!.id;
        const purse = () => state.factions.find(h => h.id === houseId)!.resources.spirit_stones;
        const before = purse();
        move(state, 1);
        expect(purse()).toBe(before);
        move(state, 169);
        expect(purse()).toBe(before);

        const db = makeDb();
        const repo = new WorldStateRepository(db);
        repo.saveWorld(state);
        const loaded = repo.loadWorld(state.id)!;
        move(state, 1);
        move(loaded, 1);
        expect(purse()).not.toBe(before);
        expect(loaded.factions).toEqual(state.factions);
        const paid = purse();
        move(state, 1);
        expect(purse()).toBe(paid);
        db.close();
    });

    it('finishes a retained war posting on its return day, once, after yearly slices and a restart', () => {
        const state = quietWorld('war-return');
        const house = state.factions[0]!;
        const home = state.locations.find(p => p.kind === 'settlement')!.id;
        const start = state.currentDay;
        const reason = getSendingReason('sending-to-a-war')!;
        const posting = postingFor({ reason, house, pitchOrdinal: 16, locationId: home });
        expect(posting.days).toBeGreaterThan(365);
        const npc = createNpc(state.seed, { id: 'retained-party', name: 'Lin Yu',
            bornOnDay: start - 30 * 365, onDay: start, factionId: house.id, locationId: home,
            cultivation: { realmOrdinal: 16 } });
        npc.activity = { kind: 'out_with_a_party', note: 'Out on the war posting.',
            withIds: [], sinceDay: start, untilDay: start + posting.days, returnTo: home };
        state.npcs = [npc];
        state.pendingSendings = [{ posting, party: [{ id: npc.id, name: npc.name, ordinal: 16 }],
            departsOnDay: start, locationId: home, counterparties: [] }];

        move(state, 365);
        expect(state.pendingSendings).toHaveLength(1);
        expect(state.npcs[0]!.activity?.kind).toBe('out_with_a_party');
        const db = makeDb();
        const repo = new WorldStateRepository(db);
        repo.saveWorld(state);
        const resumed = repo.loadWorld(state.id)!;
        move(resumed, posting.days - 366);
        expect(resumed.pendingSendings).toHaveLength(1);
        move(resumed, 1);
        expect(resumed.pendingSendings).toHaveLength(0);
        const report = resumed.history.facts.filter(f => f.day === start + posting.days
            && f.kind === reason.factKind && f.actors.some(a => a.id === npc.id));
        expect(report).toHaveLength(1);
        expect(report[0]!.truth).not.toBe('unresolved');
        expect(resumed.npcs[0]!.activity === null || isLostTrackOf(resumed, resumed.npcs[0]!)).toBe(true);
        const settled = cloneWorld(resumed);
        move(resumed, 1);
        expect(resumed.history.facts.filter(f => f.kind === reason.factKind && f.actors.some(a => a.id === npc.id))).toEqual(
            settled.history.facts.filter(f => f.kind === reason.factKind && f.actors.some(a => a.id === npc.id)));
        db.close();
    });
});
